max_width = 86
reorder_imports = true

format_code_in_doc_comments = true
group_imports = "StdExternalCrate"
imports_granularity = "Module"
overflow_delimited_expr = true
trailing_comma = "Vertical"
where_single_line = true